### ISSUE TITLE
Milestone Template Updates

### ISSUE THREAD

**Issue by widal001** [HHS/grants-api#25]
### Description

Update the milestone template to include the following changes/additions:

- [ ] Replace Delivery section with summary table at the top of the milestone definition
- [ ] Add a User Stories sub-section to the Goals section
- [ ] Promote Technical Description to its own section and add a sample sub-section for a deliverable
- [ ] Label each section as required or optional

### Definition of Done

- [ ] Changes have been applied to the template
- [ ] Changes have been reviewed and approved by @lucasmbrown-usds 
- [ ] New formatting and sections have been added to existing milestone definitions
